name: cofein
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # workspace
  serdes_json:
    path: serdes_json
  forms:
      path: forms

  flutter:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  get_it: ^5.0.1
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  optional: ^5.0.0
  localized_string: ^0.1.0
  bloc_test: ^7.0.0
  local_auth: ^0.6.3+4
  page_transition: ^1.1.5
  shared_preferences: ^0.5.8
  dio: ^3.0.9
  cryptography: ^1.4.1
  crypto_font_icons: 0.1.0
  qr_flutter: ^3.1.0
  fluttertoast: ^7.0.2
  wc_flutter_share: ^0.2.2
  flutter_svg: ^0.18.1
  permission_handler: ^5.0.1+1
  collection: ^1.14.12
  qr_code_scanner: ^0.0.13
  decimal: ^0.3.5
  fl_chart: ^0.11.1
  uuid: 2.2.2
  encrypt: ^4.0.3
  password: ^1.0.0
  simple_animations: ^2.2.2
  supercharged: ^1.10.0
  styled_widget: ^0.2.1+2
  pretty_qr_code: ^1.0.1
  alice: ^0.1.5
  webview_flutter: ^1.0.7
  pull_to_refresh: ^1.6.3

  yandex_mapkit: ^0.4.1
  sliding_sheet: ^0.2.4
  sliding_up_panel: ^1.0.0


  # Storages
  flutter_secure_storage: ^3.3.3
  hive: ^1.4.2
  hive_flutter: ^0.3.1

  cupertino_icons: ^1.0.0
  intl:
  intl_translation:

dev_dependencies:
  mockito: ^4.1.1
  build_runner:
  hive_generator: ^0.7.1
  flutter_test:
    sdk: flutter

flutter:
   uses-material-design: true
flutter_intl:
  enabled: true
